// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WC.DataAccess.SqlServer.Models;

public partial class Country
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string CountryCodeIso2 { get; set; }

    public string CountryCodeIso3 { get; set; }

    public string CountryCodeNumerical { get; set; }

    public DateTime CreationDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual ICollection<IpRange> IpRanges { get; set; } = new List<IpRange>();
}