// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WC.DataAccess.SqlServer.Models;

public partial class IpRange
{
    public int Id { get; set; }

    public int CountryId { get; set; }

    public int? IpVersion { get; set; }

    public string StartIp { get; set; }

    public string EndIp { get; set; }

    public long? StartIpNumeric { get; set; }

    public long? EndIpNumeric { get; set; }

    public byte[] StartIpBinary { get; set; }

    public byte[] EndIpBinary { get; set; }

    public bool Active { get; set; }

    public DateTime CreationDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public long? StartIpv6High { get; set; }

    public long? StartIpv6Low { get; set; }

    public long? EndIpv6High { get; set; }

    public long? EndIpv6Low { get; set; }

    public virtual Country Country { get; set; }
}