// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WC.DataAccess.SqlServer.Models;

public partial class WhichCountryContext : DbContext
{
    public WhichCountryContext(DbContextOptions<WhichCountryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<IpRange> IpRanges { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Country>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Country_Info");

            entity.ToTable("Country");

            entity.Property(e => e.CountryCodeIso2)
                .IsRequired()
                .HasMaxLength(2);
            entity.Property(e => e.CountryCodeIso3)
                .IsRequired()
                .HasMaxLength(3);
            entity.Property(e => e.CountryCodeNumerical).HasMaxLength(3);
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<IpRange>(entity =>
        {
            entity.ToTable("IpRange");

            entity.Property(e => e.Active).HasDefaultValue(true);
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EndIp)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EndIpBinary).HasMaxLength(16);
            entity.Property(e => e.StartIp)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.StartIpBinary).HasMaxLength(16);
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Country).WithMany(p => p.IpRanges)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_IpRangeCountry");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}